### ISSUE TITLE
After setting up a development new environment, tests are still failing

### ISSUE THREAD

**Issue by excalbian** [yodle/new-relic-synthetics-manager#20]
Setup a new environment with a clone of this repository and tried to run `npm test` but ran into errors because of apparently unmet dependencies. Installed the following packages with npm:

````
$ npm install gulp-cli -g
$ npm install gulp -D
$ npm install gulp-jshint -g
$ npm install jshint -g
$ npm install --save-dev jshint gulp-jshint
$ npm install -g gulp-mocha
$ npm install --save-dev gulp-mocha
$ npm install --save-dev gulp-istanbul
````
However, when I now run `npm test`,  it gives the following output but reports that the tests failed.

````
$ npm test

> new-relic-synthetics-manager@2.0.0 test /new-relic-synthetics-manager
> gulp

[05:29:44] Using gulpfile /new-relic-synthetics-manager/gulpfile.js
[05:29:44] Starting 'lint'...
[05:29:44] Starting 'pre-test'...
[05:29:44] Finished 'pre-test' after 372 ms
[05:29:44] Starting 'test'...
[05:29:44] Finished 'lint' after 406 ms
npm ERR! Test failed.  See above for more details.

$
```` 

The environment is running node.js 7.5.0 and npm 4.1.2.

**Comment by dbradf** [comment]
Have you run just `npm install` no with no arguments. That should install all the needed dependencies.

**Comment by excalbian** [comment]
@dbradf - Thank you!! I did an `npm install` and now all the tests are passing. 

FYI for anyone looking at this in the future, if you clone the repository all that is required is an `npm install` to install all the dependancies locally and then you should be able to run `npm test` successfully.
